# Use the python image runtime parent thing
FROM python:2.7-slim

# Set the working directory
WORKDIR /app

# Copy the current directory contents into the container at /app
ADD . /app

# Install the needed packages specified in requirements.txt
RUN pip install --trusted-host pypi.python.org -r requirements.txt

# Make port 80 available to the outside world
EXPOSE 80

# Define environment variables
ENV NAME World

# Run app.py when the container launches
CMD ["python", "app.py"]